config/routes.rb
Rails.application.routes.draw do
  # Admin routes
  namespace :admin do
    get '/' => 'dashboard#acquisition', as: :dashboard
    get '/dashboard/acquisition' => 'dashboard#acquisition', as: :acquisition_dashboard
    get '/dashboard/migration' => 'dashboard#migration', as: :migration_dashboard
    get '/dashboard/usage' => 'dashboard#usage', as: :usage_dashboard
    resources :organizations
    resources :users do
      member do
        post :log_in_as_user
        put :restore, as: :restore
        post :send_reset
        post :verify_email
        post :reset_api_token
        delete :hard_delete
      end
    end
    resources :teams
    resource :app_settings, path: 'settings'
    resource :session, only: [:new, :create]
    resources :intercom_queues, only: [:index]

    # mount sidekiq web and protect behind admin auth ... if first route fails due
    # to constraint it will route to the dashboard and prompt for admin login
    require 'sidekiq/web'
    require 'admin_constraint'
    mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
    get '/sidekiq', to: 'dashboard#acquisition'
  end
  # This route is exposed by omniauth so needs to live outside the admin namespace
  get '/auth/admin/callback' => 'admin/sessions#create'

  # migration routes
  get '/migrate' => 'migration#connect'
  get '/migrate/confirm' => 'migration#confirm'
  post '/migrate' => 'migration#execute_migration'
  get '/auth/idonethis/callback' => 'migration#oauth_callback'

  # Onboarding
  get 'migrate/one' => 'onboard#migrate_one'
  patch 'migrate/one' => 'onboard#migrate_one_save'
  get 'migrate/two' => 'onboard#migrate_two'
  patch 'migrate/two' => 'onboard#migrate_two_save'

  get 'onboard/one' => 'onboard#onboard_one'
  patch 'onboard/one' => 'onboard#onboard_one_save'
  get 'onboard/two' => 'onboard#onboard_two'
  patch 'onboard/two' => 'onboard#onboard_two_save'
  patch 'onboard/exit' => 'onboard#onboard_exit'
  get 'onboard/notice' => 'onboard#onboard_notice'

  # standard user dashboard

  resources :organizations, only: [:new, :create, :show, :update], path: 'o' do
    member do
      get :overdue
      get :stats
      get :export
      get :settings
      get :billing # partial
      get :billing_form # partial
      patch :billing_save # partial
      patch :saml_save # partial
      patch :customize
      get :invoices # partial
    end

    resources :teams, path: 't', only: [:new, :create]
    resources :users, path: 'u'
    resources :organization_memberships, path: 'memberships', only: [:index, :update, :destroy]
    resources :tags, only: [:show]
    resources :invitations, only: [:new, :create]
  end

  resources :teams, path: 't', only: [:show, :update, :destroy] do
    member do
      get :search
      get :stats
      get :calendar
      get :export
      get :settings
      post :join
      patch :customize # partial
      get :calendar_month # partial
      get :brief # partial
    end

    resources :tags, only: [:show]
    resources :entries, only: [:create, :update]
    resources :team_memberships, path: 'memberships', only: [:new, :create, :update, :destroy, :index] do
      member do
        get :notifications # partial
        patch :notifications_save # partial
        get :unsubscribe_comments_notification
        get :unsubscribe_mentions_notification
        get :unsubscribe_digests
        get :unsubscribe_reminders
        patch :unthrottle_emails
        get :unsubscribe_assign_task_reminders
      end
    end
    resources :invitations, only: [:create]
  end

  resources :entries, path: 'e', only: [:show, :edit, :destroy] do
    member do
      get :brief # partial
      get :assign # partial
      post :toggle_like # partial
      post :mark_done # partial
      post :archive # partial
    end
    resources :reactions, only: [:create, :update, :destroy] # partial
  end

  resources :reactions, only: [:show, :edit], path: 'r'

  resource :user, only: [:update], path: 'u' do
    member do
      post :go_by_for_full_name

      get :settings
      patch :personalize
      patch :change_password
    end
  end

  resources :integrations, only: [:index]
  resources :invitations, only: [:destroy], path: 'i' do
    member do
      post :resend
      patch :accept
      patch :decline
    end
  end

  resources :alternate_emails, only: [:create, :destroy]
  get 'alternate_emails/:verification_code/verify', to: 'alternate_emails#verify', as: :verify_alternate_email
  
  resources :notifications, only: [:index, :destroy]

  post 'notifications' => 'notifications#clear'
  get 'notifications/reload_archived' => 'notifications#reload_archived'
  patch 'entry_listing' => 'teams#user_entry_listing'
  root 'organizations#default'

  # User & Auth

  ## Use doorkeeper for OAuth provider functionality
  use_doorkeeper

  ## SAML SSO routes
  resources :saml, only: [] do
    collection do
      get  'sso/:id' => 'saml#sso'
      post 'consume/:id' => 'saml#consume'
      get  'metadata/:id' => 'saml#metadata'
    end
  end

  ## Upgrade to $$ plan

  get 'o/:organization_id/upgrade/subcription_failes' => 'upgrade#subcription_failes', as: :subcription_failes
  get 'o/:organization_id/upgrade' => 'upgrade#show', as: :organization_upgrade
  get 'o/:organization_id/upgrade/billing' => 'upgrade#billing', as: :organization_upgrade_billing
  patch 'o/:organization_id/upgrade/complete' => 'upgrade#complete', as: :organization_upgrade_complete
  ## Normal user+session management routes
  resources :users, only: [:create] do
    collection do
      get 'reset_password' => 'users#request_reset'
      post 'reset_password' => 'users#request_reset'
      patch 'reset_api_token' => 'users#reset_api_token'
      get 'reset_password/:password_reset_token' => 'users#reset_password', as: :reset
      post 'reset_password/:password_reset_token' => 'users#reset_password'
      get 'verify/:verification_token' => 'users#verify', as: :verify
    end
  end

  get 'register(/:invitation_code)' => 'users#new', as: :register
  resources :user_sessions, only: [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout
  get  '/auth/:provider' => "user_sessions#oauth", as: :auth_at_provider
  get  '/auth/google/callback' => 'user_sessions#oauth_callback'

  # API Routes
  namespace :api do
    namespace :v2 do
      get 'noop' => 'noop#index'
      post 'login' => 'sessions#create'
      post 'logout' => 'sessions#destroy', as: :logout
      post 'gmail_login' => 'sessions#gmail_login'
      resources :entries, only: [:index, :create, :show, :update, :destroy] do
        member do
          get :assign
          post :toggle_like
          post :mark_done
        end
        collection do
          get 'date_wise_entry_list' => 'entries#date_wise_entry_list'
        end
      end
      resources :hooks, only: [:index, :create, :show, :update, :destroy]
      resources :team_memberships, only: [:create,:update,:destroy] do 
        member do
          patch :notifications_save
        end
        collection do
          get 'fetch_team_membership' => 'team_memberships#fetch_team_membership'
        end
      end
      resources :teams, only: [:create, :index, :show, :update] do
        member do
          get :members
          get :entries
        end
      end
      resources :users do
        collection do
          get :request_reset
        end
        member do
          post :personalize
        end
      end
      resources :reactions
      resources :organizations, only: [:show] do
        collection do
          get :user_org
        end
      end

    end
  end

  ## Slack
  get    '/auth/slack/callback'     => 'integrations/slack#oauth_callback'
  get    '/integrations/slack/link' => 'integrations/slack#new_link'
  post   '/integrations/slack/link' => 'integrations/slack#create_link'
  delete '/integrations/slack/link' => 'integrations/slack#destroy_link'
  post   '/integrations/slack/hook' => 'integrations/slack#hook'
  ## Github
  get    '/auth/github/callback'     => 'integrations/github#oauth_callback'
  get    '/integrations/github/link' => 'integrations/github#new_link'
  post   '/integrations/github/link' => 'integrations/github#create_link'
  delete '/integrations/github/link' => 'integrations/github#destroy_link'
  post   '/integrations/github/hook/:token' => 'integrations/github#hook'
  ## Inbound Email
  post '/integrations/inbound_emails' => 'integrations/inbound_emails#create'
  ## Stripe Webhooks
  post '/stripe/hook' => 'stripe#hook'

  # Error routes
  get "/todo" => "errors#todo"
  get "/incorrect_organization" => "errors#incorrect_organization"
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  # Static pages
  get '/about' => 'pages#about'
end

app/models/concerns/idt_intercom/organization.rb
module IdtIntercom::Organization
  extend ActiveSupport::Concern
  included do
    after_update :queue_intercom, if: :subscription_changed?
  end

  private
  def queue_intercom
    self.owners.each do |owner|
      IntercomQueue.find_or_create_by(user_id: owner.id)
    end
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::ApplicationController
  def index
    if params[:filter_field].present? &&
       (params[:filter_field].downcase != 'all') &&
       Organization.filter_fields.include?(params[:filter_field].downcase)

      @organizations = Organization.alphabetically.advanced_search(params[:filter_field].to_sym => params[:filter_value]).page(params[:page])
      @scope_count = Organization.alphabetically.advanced_search(params[:filter_field].to_sym => params[:filter_value]).size
      @filter_params = params.slice(:filter_field, :filter_value)

      if @organizations.size == 1
        redirect_to [:admin, @organizations.first]
        return
      end
    else
      @scope_count = Organization.alphabetically.count
      @organizations = Organization.alphabetically.page(params[:page])
    end
  end

  def show
    @filter_params = params.slice(:filter_field, :filter_value)
    @organization = Organization.find_by(hash_id: params[:id])
  end

  def update
    @organization = Organization.find_by(hash_id: params[:id])
    @organization.update_attributes(organization_params)
    redirect_to [:admin, @organization]
  end

  def destroy
    @organization = Organization.find_by(hash_id: params[:id])
    @organization.destroy
    redirect_to [:admin, :organizations], notice: "#{@organization.name} deleted"
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name,
      :saml_meta_url,
      :trial_ends_at
    )
  end
end

app/controllers/api/v2/organizations_controller.rb
class Api::V2::OrganizationsController < Api::V2::BaseController
	
	def user_org
		@user_organizations = @current_user.active_organizations
		render formats: :json
	end
	# GET
	# http://localhost:3000/api/v2/organizations?api_token=db4de0d2886f486f2a2d24e0f5cfed305740eacd&id=awecwrwacwqecw709c6qwcw87r6wcrq
	def show
    @organization = Organization.find_by(hash_id: params[:id])
		@teams = @organization.teams
		@org_team_arr = []
		@teams.each do |team|
			@users = team.users
			@users.each do |user|
				if user.id == @current_user.id
					@org_team_arr << team
				end
			end
		end
	  render formats: :json
	end
end

app/helpers/organization_helper.rb
module OrganizationHelper

  def current_active_organization
    last_team_visited = if cookies[:last_team_id].present? && cookies[:last_team_id] == params[:id] ||= params[:team_id]
                          current_user.active_teams.where(hash_id: cookies[:last_team_id]).first
                        end
    if last_team_visited.present?
      last_team_visited&.organization
    elsif params[:id].present?
      Organization.find_by(hash_id: params[:id] ||= params[:organization_id])
    else
      current_user.organizations.last
    end
  end
end

app/views/admin/organizations/_organization.html.haml
%li.admin-list_item.admin-list-users_item
  = link_to admin_organization_path(organization, @filter_params) do
    %big= organization.name.present? ? organization.name : 'Untitled'
    %dl
      %dt Members
      %dd= organization.active_users.count
      %dt Created
      %dd= organization.created_at.strftime("%b %d '%y")
      %dt Teams
      %dd= organization.teams.count
      %dt Entries
      %dd= organization.entries.count

app/views/admin/organizations/index.html.haml
:coffeescript
  $ ->
    for form in $('.admin-pane-filter form')
      filterForm = $(form)
      fieldVal = $('[name="filter_field"]:first', filterForm).val()
      if (fieldVal.length == 0) or (fieldVal == 'All')
        $('[name="filter_value"]').hide()
        $('[name="filter_value"]').val('')
      else
        $('[name="filter_value"]').show()

    $('[name="filter_field"]').on 'change', (e) ->
      if ($(e.currentTarget).val().length == 0) or ($(e.currentTarget).val() == 'All')
        $('[name="filter_value"]').hide()
        $('[name="filter_value"]').val('')
        location.reload()
      else
        $('[name="filter_value"]').show()

- content_for :header do
  %div.breadcrumbs
    = link_to "Organizations", [:admin, :organizations]

.wrapper-small{role: 'layout'}
  .admin-pane
    .admin-pane-header
      %nav.admin-pane-filter
        %form{method: 'get'}
          %label Filter:
          %select{name: 'filter_field'}
            %option All
            - Organization.filter_fields.each do |filter_field|
              %option{value: filter_field, selected: (filter_field == params[:filter_field]) ? 'selected' : nil}= filter_field

          %input{name: 'filter_value', value: params[:filter_value]}

      %header.admin-pane-results
        %p.total-results= pluralize @scope_count, 'organization'
        = paginate @organizations

    %ul.admin-list.admin-list-organizations= render @organizations

app/views/admin/organizations/show.html.haml
- content_for :header do
  %div.breadcrumbs
    = link_to "Organizations", [:admin, :organizations]

    - if params[:filter_field].present? && params[:filter_value]
      = link_to "#{ params[:filter_field] }: #{ params[:filter_value] }", admin_users_path(filter_field: params[:filter_field], filter_value: params[:filter_value])

    = link_to @organization.name, [:admin, @organization]

.wrapper-small{role: 'layout'}
  .admin-pane
    %header.admin-show_header
      %h1= @organization.name

    %nav.admin-nav
      - if @organization.owners.any?
        = link_to "Log in as an owner", log_in_as_user_admin_user_path(@organization.owners.first), method: 'post', class: 'button utility'
      - if @organization.stripe_customer_token.present?
        = link_to "View in Stripe", "https://dashboard.stripe.com/customers/#{ @organization.stripe_customer_token }", class: 'button utility'
      = link_to "Permanently Delete", [:admin, @organization], method: 'delete', class: 'button utility', data: { confirm: 'This is permanent, irreversible, and potentially catostrophic. You should probably click cancel.' }

    %main.admin-show_main
      = form_for [:admin, @organization] do |f|
        %table.admin-table
          %tr
            %th= f.label :id
            %td= f.text_field :id, readonly: true
          %tr
            %th= f.label :name
            %td= f.text_field :name
          %tr
            %th= f.label :saml_meta_url
            %td= f.text_field :saml_meta_url
          %tr
            %th= f.label :autojoin_domain
            %td= f.text_field :autojoin_domain
          %tr
            %th= f.label :billing_name
            %td= f.text_field :billing_name
          %tr
            %th= f.label :billing_email_address
            %td= f.text_field :billing_email_address
          %tr
            %th
              %label Subscription quantity
            %td
              %input{readonly: true, type: 'text', value: @organization.active_users.count}
          %tr
            %th= f.label :plan_level
            %td= f.text_field :plan_level, readonly: true
          %tr
            %th= f.label :plan_interval
            %td= f.text_field :plan_interval, readonly: true
          %tr
            %th= f.label :trial_ends_at
            %td
              = f.date_field :trial_ends_at, min: Date.tomorrow,
                readonly: @organization.stripe_subscription_status.present? && @organization.stripe_subscription_status != 'trialing'
              %p.help-text Can only be updated to a date in the future, sorry.
          %tr
            %th= f.label :stripe_subscription_status
            %td= f.text_field :stripe_subscription_status, readonly: true
          %tr
            %th
              %label Total entries
            %td
              %input{readonly: true, type: 'text', value: @organization.entries.count}
          %tr
            %th
              %label Teams
            %td= @organization.teams.map { |t| link_to(t.name, [:admin,t]) }.join(', ').html_safe
          %tr
            %th
              %label Owners
            %td= @organization.owners.map { |u| link_to(u.full_name_or_something_else_identifying, [:admin,u]) }.join(', ').html_safe
          %tr
            %th
              %label Admins
            %td= @organization.admins.map { |u| link_to(u.full_name_or_something_else_identifying, [:admin,u]) }.join(', ').html_safe
          %tr
            %th
              %label Active Members
            %td= @organization.active_users.map { |u| link_to(u.full_name_or_something_else_identifying, [:admin,u]) }.join(', ').html_safe
          %tr
            %th
              %label Removed Members
            %td= @organization.removed_users.map { |u| link_to(u.full_name_or_something_else_identifying, [:admin,u]) }.join(', ').html_safe
          %tr
            %th
              %label Deleted Members
            %td= @organization.users.only_deleted.map { |u| link_to(u.full_name_or_something_else_identifying, [:admin,u]) }.join(', ').html_safe
        %nav.actions
          = f.submit 'Save changes', class: 'button'