config/routes.rb
Rails.application.routes.draw do
  # Admin routes
  namespace :admin do
    get '/' => 'dashboard#acquisition', as: :dashboard
    get '/dashboard/acquisition' => 'dashboard#acquisition', as: :acquisition_dashboard
    get '/dashboard/migration' => 'dashboard#migration', as: :migration_dashboard
    get '/dashboard/usage' => 'dashboard#usage', as: :usage_dashboard
    resources :organizations
    resources :users do
      member do
        post :log_in_as_user
        put :restore, as: :restore
        post :send_reset
        post :verify_email
        post :reset_api_token
        delete :hard_delete
      end
    end
    resources :teams
    resource :app_settings, path: 'settings'
    resource :session, only: [:new, :create]
    resources :intercom_queues, only: [:index]

    # mount sidekiq web and protect behind admin auth ... if first route fails due
    # to constraint it will route to the dashboard and prompt for admin login
    require 'sidekiq/web'
    require 'admin_constraint'
    mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
    get '/sidekiq', to: 'dashboard#acquisition'
  end
  # This route is exposed by omniauth so needs to live outside the admin namespace
  get '/auth/admin/callback' => 'admin/sessions#create'

  # migration routes
  get '/migrate' => 'migration#connect'
  get '/migrate/confirm' => 'migration#confirm'
  post '/migrate' => 'migration#execute_migration'
  get '/auth/idonethis/callback' => 'migration#oauth_callback'

  # Onboarding
  get 'migrate/one' => 'onboard#migrate_one'
  patch 'migrate/one' => 'onboard#migrate_one_save'
  get 'migrate/two' => 'onboard#migrate_two'
  patch 'migrate/two' => 'onboard#migrate_two_save'

  get 'onboard/one' => 'onboard#onboard_one'
  patch 'onboard/one' => 'onboard#onboard_one_save'
  get 'onboard/two' => 'onboard#onboard_two'
  patch 'onboard/two' => 'onboard#onboard_two_save'
  patch 'onboard/exit' => 'onboard#onboard_exit'
  get 'onboard/notice' => 'onboard#onboard_notice'

  # standard user dashboard

  resources :organizations, only: [:new, :create, :show, :update], path: 'o' do
    member do
      get :overdue
      get :stats
      get :export
      get :settings
      get :billing # partial
      get :billing_form # partial
      patch :billing_save # partial
      patch :saml_save # partial
      patch :customize
      get :invoices # partial
    end

    resources :teams, path: 't', only: [:new, :create]
    resources :users, path: 'u'
    resources :organization_memberships, path: 'memberships', only: [:index, :update, :destroy]
    resources :tags, only: [:show]
    resources :invitations, only: [:new, :create]
  end

  resources :teams, path: 't', only: [:show, :update, :destroy] do
    member do
      get :search
      get :stats
      get :calendar
      get :export
      get :settings
      post :join
      patch :customize # partial
      get :calendar_month # partial
      get :brief # partial
    end

    resources :tags, only: [:show]
    resources :entries, only: [:create, :update]
    resources :team_memberships, path: 'memberships', only: [:new, :create, :update, :destroy, :index] do
      member do
        get :notifications # partial
        patch :notifications_save # partial
        get :unsubscribe_comments_notification
        get :unsubscribe_mentions_notification
        get :unsubscribe_digests
        get :unsubscribe_reminders
        patch :unthrottle_emails
        get :unsubscribe_assign_task_reminders
      end
    end
    resources :invitations, only: [:create]
  end

  resources :entries, path: 'e', only: [:show, :edit, :destroy] do
    member do
      get :brief # partial
      get :assign # partial
      post :toggle_like # partial
      post :mark_done # partial
      post :archive # partial
    end
    resources :reactions, only: [:create, :update, :destroy] # partial
  end

  resources :reactions, only: [:show, :edit], path: 'r'

  resource :user, only: [:update], path: 'u' do
    member do
      post :go_by_for_full_name

      get :settings
      patch :personalize
      patch :change_password
    end
  end

  resources :integrations, only: [:index]
  resources :invitations, only: [:destroy], path: 'i' do
    member do
      post :resend
      patch :accept
      patch :decline
    end
  end

  resources :alternate_emails, only: [:create, :destroy]
  get 'alternate_emails/:verification_code/verify', to: 'alternate_emails#verify', as: :verify_alternate_email
  
  resources :notifications, only: [:index, :destroy]

  post 'notifications' => 'notifications#clear'
  get 'notifications/reload_archived' => 'notifications#reload_archived'
  patch 'entry_listing' => 'teams#user_entry_listing'
  root 'organizations#default'

  # User & Auth

  ## Use doorkeeper for OAuth provider functionality
  use_doorkeeper

  ## SAML SSO routes
  resources :saml, only: [] do
    collection do
      get  'sso/:id' => 'saml#sso'
      post 'consume/:id' => 'saml#consume'
      get  'metadata/:id' => 'saml#metadata'
    end
  end

  ## Upgrade to $$ plan

  get 'o/:organization_id/upgrade/subcription_failes' => 'upgrade#subcription_failes', as: :subcription_failes
  get 'o/:organization_id/upgrade' => 'upgrade#show', as: :organization_upgrade
  get 'o/:organization_id/upgrade/billing' => 'upgrade#billing', as: :organization_upgrade_billing
  patch 'o/:organization_id/upgrade/complete' => 'upgrade#complete', as: :organization_upgrade_complete
  ## Normal user+session management routes
  resources :users, only: [:create] do
    collection do
      get 'reset_password' => 'users#request_reset'
      post 'reset_password' => 'users#request_reset'
      patch 'reset_api_token' => 'users#reset_api_token'
      get 'reset_password/:password_reset_token' => 'users#reset_password', as: :reset
      post 'reset_password/:password_reset_token' => 'users#reset_password'
      get 'verify/:verification_token' => 'users#verify', as: :verify
    end
  end

  get 'register(/:invitation_code)' => 'users#new', as: :register
  resources :user_sessions, only: [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout
  get  '/auth/:provider' => "user_sessions#oauth", as: :auth_at_provider
  get  '/auth/google/callback' => 'user_sessions#oauth_callback'

  # API Routes
  namespace :api do
    namespace :v2 do
      get 'noop' => 'noop#index'
      post 'login' => 'sessions#create'
      post 'logout' => 'sessions#destroy', as: :logout
      post 'gmail_login' => 'sessions#gmail_login'
      resources :entries, only: [:index, :create, :show, :update, :destroy] do
        member do
          get :assign
          post :toggle_like
          post :mark_done
        end
        collection do
          get 'date_wise_entry_list' => 'entries#date_wise_entry_list'
        end
      end
      resources :hooks, only: [:index, :create, :show, :update, :destroy]
      resources :team_memberships, only: [:create,:update,:destroy] do 
        member do
          patch :notifications_save
        end
        collection do
          get 'fetch_team_membership' => 'team_memberships#fetch_team_membership'
        end
      end
      resources :teams, only: [:create, :index, :show, :update] do
        member do
          get :members
          get :entries
        end
      end
      resources :users do
        collection do
          get :request_reset
        end
        member do
          post :personalize
        end
      end
      resources :reactions
      resources :organizations, only: [:show] do
        collection do
          get :user_org
        end
      end

    end
  end

  ## Slack
  get    '/auth/slack/callback'     => 'integrations/slack#oauth_callback'
  get    '/integrations/slack/link' => 'integrations/slack#new_link'
  post   '/integrations/slack/link' => 'integrations/slack#create_link'
  delete '/integrations/slack/link' => 'integrations/slack#destroy_link'
  post   '/integrations/slack/hook' => 'integrations/slack#hook'
  ## Github
  get    '/auth/github/callback'     => 'integrations/github#oauth_callback'
  get    '/integrations/github/link' => 'integrations/github#new_link'
  post   '/integrations/github/link' => 'integrations/github#create_link'
  delete '/integrations/github/link' => 'integrations/github#destroy_link'
  post   '/integrations/github/hook/:token' => 'integrations/github#hook'
  ## Inbound Email
  post '/integrations/inbound_emails' => 'integrations/inbound_emails#create'
  ## Stripe Webhooks
  post '/stripe/hook' => 'stripe#hook'

  # Error routes
  get "/todo" => "errors#todo"
  get "/incorrect_organization" => "errors#incorrect_organization"
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  # Static pages
  get '/about' => 'pages#about'
end

app/controllers/onboard_controller.rb
class OnboardController < ApplicationController
  layout 'onboarding'
  before_action :require_login
  ## Onboard new users

  def onboard_notice
      @user = current_user
      authorize @user
      logger.info("--Userrrr login 144----")
      render action: 'onboard_notice'
  end

  def onboard_one
    @user = current_user

    authorize @user
    if @user.active_organizations.any? # if somebody's been invited and is already in an org
      @user.touch(:onboarded_at)
      redirect_to(root_path) && return
    end
  end

  def onboard_one_save
    @user = current_user

    authorize @user
    if @user.update_attributes(onboard_user_params)
      if @user.teams.non_personal.any?
        @team = @user.teams.last
        entry_titles = []
        if cookies[:new_goal].present?
          entry_titles << cookies[:new_goal]
          cookies.delete :new_goal
        end
        CreateTipsEntriesWorker.perform_async("#{request.base_url}/t/",
                                              current_user.id,
                                              current_user.time_zone,
                                              @team.id,
                                              @team.hash_id,
                                              entry_titles)
        @organization = @team.organization
        @organization.plan_level = "small"
        @organization.plan_interval = "monthly"
        subscription = Stripe::Subscription.create({
          customer: @organization.stripe_customer_token,
          plan:     @organization.plan_stripe_id,
          quantity: @organization.users.count,
          trial_end: @organization.on_trial? ? @organization.trial_ends_at.to_i : 'now',
        })
        @organization.stripe_subscription_status = subscription.status
        @organization.save
        redirect_to('/onboard/two')
      else
        @user.touch(:onboarded_at)
        redirect_to root_path
      end
    else
      render action: 'onboard_one'
    end
  end

  def onboard_two
    @user = current_user
    @team = @user.teams.last
    @organization = @team.organization

    authorize @user
  end

  def onboard_two_save
    user = current_user
    team = user.teams.last
    organization = team.organization

    invitations = []
    team_memberships = []

    invitation_params[:email_addresses].split(',').uniq.map(&:strip).each do |email_address|
      existing_user = organization.active_users.find_by(email_address: email_address)
      if existing_user.present?
        team_memberships << TeamMembership.find_or_initialize_by(team_id: team.id, user_id: existing_user.id)
      else
        invitations << Invitation.new(organization: organization, sender: current_user, email_address: email_address, team_ids: [team.id])
      end
    end

    authorize user

    team_memberships.each(&:join!)
    invitations.each(&:save!)

    user.touch(:onboarded_at)
    redirect_to root_path
  end

  def onboard_exit
    @user = current_user

    authorize @user
    @user.touch(:onboarded_at)

    redirect_to root_path
  end


  ## Onboard migrated users

  def migrate_one
    @user = current_user

    authorize @user
  end

  def migrate_one_save
    @user = current_user

    authorize @user

    if @user.update_attributes(migrate_user_params)
      redirect_to('/migrate/two')
    else
      render action: 'migrate_one'
    end
  end

  def migrate_two
    @user = current_user

    authorize @user
  end

  def migrate_two_save
    @user = current_user

    authorize @user

    if @user.touch(:onboarded_at)
      redirect_to root_path
    else
      render action: 'migrate_two'
    end
  end

  private

  def onboard_user_params
    params.require(:user).permit(:full_name, :go_by_name, :portrait, :first_team_name)
  end

  def migrate_user_params
    params.require(:user).permit(:full_name, :go_by_name, :portrait)
  end

  def invitation_params
    params.require(:invitations).permit(:email_addresses)
  end
end

app/views/onboard/migrate_one.html.haml
:coffeescript
  $ ->
    $('.uploader').on 'click', '.portrait-placeholder', (e) ->
      $(e.currentTarget).siblings('[type="file"]:first').click()

    $('[data-bind="goBySuggestion"]').on 'click', '[data-action="yes"]', (e) ->
      $('.fieldlet.go-by').hide()

    $('[data-bind="goBySuggestion"]').on 'click', '[data-action="no"]', (e) ->
      $('[data-bind="goBySuggestion"]:first').hide()
      $('[data-bind="goByOverride"]:first').show()

    $('.uploader [type="file"]').on 'change', (e) ->
      reader = new FileReader

      reader.onload = (re) ->
        $('.uploader:first .portrait-placeholder:first').attr('style', "background-image: url('" + re.target.result + "'); background-size: cover;")

      reader.readAsDataURL @files[0]

    $('[name="user[full_name]"]').on 'blur', (e) ->
      fullNameVal = $(e.currentTarget).val()
      $.post ('#{ go_by_for_full_name_user_path }'), {full_name: fullNameVal}, (data) ->
        if data.length > 0
          $('.fieldlet.go-by').show()
          $('[data-bind="user[go_by_name]"]:first').text data
          $('[name="user[go_by_name]"]:first').val data
        else
          $('.fieldlet.go-by').hide()

.wrapper-small{role: 'layout'}
  .onboard-content
    %header.onboard-header
      %h1 Welcome to <strong>I Done This</strong>

    .onboard-panel
      = form_for @user, url: '/migrate/one', html: { class: 'onboard-form' } do |f|
        %main
          :markdown
            Welome to this brand-new version of **I Done This**. Really quick &mdash; can you confirm a few details?

          - if @user.errors.any?
            %ul.list-errors
              - @user.errors.full_messages.each do |msg|
                %li= msg

          .field
            - if @user.full_name.present?
              = f.label :full_name, 'Is this your full name?'
            - else
              = f.label :full_name, 'What is your full name?'
            = f.text_field :full_name, placeholder: "Jane Smith"

            .fieldlet.go-by{style: @user.go_by_name.present? ? nil : 'display:none'}
              %p{'data-bind' => 'goBySuggestion'}
                = f.hidden_field :go_by_name
                %span{'data-bind' => 'goByQuestion'} Can we call you <strong data-bind='user[go_by_name]'>#{ @user.go_by_name }</strong>?
                %a{'data-action' => 'yes'} Yes
                %a{'data-action' => 'no'} No

              %p{'data-bind' => 'goByOverride', style: 'display:none'}
                = f.label :go_by_name, 'I prefer to go by'
                = f.text_field :go_by_name, placeholder: "Jane"

        %aside
          .uploader
            - if @user.portrait.present?
              %div.portrait-placeholder{style: "background-image: #{ asset_url(@user.portrait.url) }; background-size: fill;"}
            - else
              %div.portrait-placeholder

            %label Upload a portrait. Smile!
            = f.hidden_field(:portrait_cache)
            = f.file_field(:portrait)

        %nav
          .actions= f.submit 'Continue', class: 'button'

app/views/onboard/migrate_two.html.haml
.wrapper-small{role: 'layout'}
  .onboard-content
    - if ((Time.zone.now - @user.created_at) > 1.week)
      %header.onboard-header
        %h1 New icons and blockers

      .onboard-primer
        %div.onboard-primer_status-types
          %section.onboard-primer_status-type
            %div.onboard-primer_status-type-icon.onboard-primer_status-type-icon_done{style: "background-image: url('#{ asset_path 'icon-done-white.svg' }')"}
            %h3 Done
            :markdown
              Something you've completed

          %section.onboard-primer_status-type
            %div.onboard-primer_status-type-icon.onboard-primer_status-type-icon_goal{style: "background-image: url('#{ asset_path 'icon-goal-white.svg' }')"}
            %h3 Goal
            :markdown
              Something you plan to get do

          %section.onboard-primer_status-type
            %div.onboard-primer_status-type-icon.onboard-primer_status-type-icon_blocked{style: "background-image: url('#{ asset_path 'icon-blocked-white.svg' }')"}
            %h3 Blocked
            :markdown
              Something you can't get done

        %article.onboard-primer_article
          :markdown
            ## Get to know the new entry icons

            Also — check it out: we've introduced blocked entries. A blocked entry is something that you can't get done, usually for an external reason (like it's dependent on something somebody else is working on).

          %nav.onboard-primer_nav
            .actions
              = form_for @user, url: '/migrate/two' do |f|
                = f.hidden_field :onboarded_at
                = f.submit "Got it — get started", class: 'button'

    - else

      %header.onboard-header
        %h1 Welcome to <strong>I Done This</strong>

      .onboard-primer
        %div.onboard-primer_status-types
          %section.onboard-primer_status-type
            %div.onboard-primer_status-type-icon.onboard-primer_status-type-icon_done{style: "background-image: url('#{ asset_path 'icon-done-white.svg' }')"}
            %h3 Done
            :markdown
              Something you've completed

          %section.onboard-primer_status-type
            %div.onboard-primer_status-type-icon.onboard-primer_status-type-icon_goal{style: "background-image: url('#{ asset_path 'icon-goal-white.svg' }')"}
            %h3 Goal
            :markdown
              Something you plan to get do

          %section.onboard-primer_status-type
            %div.onboard-primer_status-type-icon.onboard-primer_status-type-icon_blocked{style: "background-image: url('#{ asset_path 'icon-blocked-white.svg' }')"}
            %h3 Blocked
            :markdown
              Something you can't get done

        %article.onboard-primer_article
          :markdown
            ## Get to know the entry types

            Everything you enter in your daily check-in is either something you've gotten done, something you plan to get done, or something you can't get done — usually for an external reason (like it's dependent on something somebody else is working on).

          %nav.onboard-primer_nav
            .actions
              = form_for @user, url: '/migrate/two' do |f|
                = f.hidden_field :onboarded_at
                = f.submit "Got it — get started", class: 'button'

app/views/onboard/onboard_notice.html.haml
:coffeescript
  $ ->
    $('.uploader').on 'click', '.portrait-placeholder', (e) ->
      $(e.currentTarget).siblings('[type="file"]:first').click()

    $('[data-bind="goBySuggestion"]').on 'click', '[data-action="yes"]', (e) ->
      $('.fieldlet.go-by').css('opacity','0')

    $('[data-bind="goBySuggestion"]').on 'click', '[data-action="no"]', (e) ->
      $('[data-bind="goBySuggestion"]:first').css('opacity','0')
      $('[data-bind="goByOverride"]:first').css('opacity','1')

    $('.uploader [type="file"]').on 'change', (e) ->
      reader = new FileReader

      reader.onload = (re) ->
        $('.uploader:first .portrait-placeholder:first').attr('style', "background-image: url('" + re.target.result + "'); background-size: cover;")

      reader.readAsDataURL @files[0]

    $('[name="user[full_name]"]').on 'blur', (e) ->
      fullNameVal = $(e.currentTarget).val()
      $.post ('#{ go_by_for_full_name_user_path }'), {full_name: fullNameVal}, (data) ->
        if data.length > 0
          $('.fieldlet.go-by').css('opacity','1')
          $('[data-bind="user[go_by_name]"]:first').text data
          $('[name="user[go_by_name]"]:first').val data
        else
          $('.fieldlet.go-by').css('opacity','0')

.wrapper-small{role: 'layout'}
  .onboard-content
    %header.onboard-header
      %h1 Welcome to <strong>I Done This</strong>

    .onboard-warning{ :style=>"background:white;padding: 25px;text-align: justify;"}
      %strong{:class => "code", :id => "message"} As we continue to focus our resources on product development, we will no longer offer our free plan as of April 21st, 2019. To continue enjoying the benefits of IDoneThis, all free users will need to sign up for a paid subscription plan option by this date. Please note that we’ve recently added a “Small” plan for only $12.50 per month.
      %br/ 
      %br/ 
      %br/ 
      %br/ 
      
      =button_to 'Subscribe Now',{:controller => 'onboard', :action => 'onboard_one'}, {:class => 'your button class', :method => 'get', :style => 'cursor:pointer;float: right;margin-top: -50px;'}
      %br/ 
      = link_to 'Skip for now', root_path,style: 'cursor:pointer;float: right;margin-top: -15px;'
      =# button_to 'Subscribe Now',{:controller => 'onboard', :action => 'onboard_one'}, {:class => 'your button class', :method => 'get', :style => 'cursor:pointer;float: right;margin-top: -50px;'}

app/views/onboard/onboard_one.html.haml
:coffeescript
  $ ->
    $('.onboard-one-button').on 'click', (e) ->
      e.stopPropagation()
      e.preventDefault()
      btn = $(e.currentTarget)
      btn.val('···')
      btn.attr('disabled', true)
      setTimeout (->
        $('.onboard-one-form').submit()
      ), 500

    $('.uploader').on 'click', '.portrait-placeholder', (e) ->
      $(e.currentTarget).siblings('[type="file"]:first').click()

    $('[data-bind="goBySuggestion"]').on 'click', '[data-action="yes"]', (e) ->
      $('.fieldlet.go-by').css('opacity','0')

    $('[data-bind="goBySuggestion"]').on 'click', '[data-action="no"]', (e) ->
      $('[data-bind="goBySuggestion"]:first').css('opacity','0')
      $('[data-bind="goByOverride"]:first').css('opacity','1')

    $('.uploader [type="file"]').on 'change', (e) ->
      reader = new FileReader

      reader.onload = (re) ->
        $('.uploader:first .portrait-placeholder:first').attr('style', "background-image: url('" + re.target.result + "'); background-size: cover;")

      reader.readAsDataURL @files[0]

    $('[name="user[full_name]"]').on 'blur', (e) ->
      fullNameVal = $(e.currentTarget).val()
      $.post ('#{ go_by_for_full_name_user_path }'), {full_name: fullNameVal}, (data) ->
        if data.length > 0
          $('.fieldlet.go-by').css('opacity','1')
          $('[data-bind="user[go_by_name]"]:first').text data
          $('[name="user[go_by_name]"]:first').val data
        else
          $('.fieldlet.go-by').css('opacity','0')

.wrapper-small{role: 'layout'}
  .onboard-content
    %header.onboard-header
      %h1 Welcome to <strong>I Done This</strong>

    .onboard-panel
      = form_for @user, url: '/onboard/one', html: { class: 'onboard-form onboard-one-form' } do |f|
        %main
          - if @user.errors.any?
            %ul.list-errors
              - @user.errors.full_messages.each do |msg|
                %li= msg

          .field
            - if @user.full_name.present?
              = f.label :full_name, 'Is this your full name?'
            - else
              = f.label :full_name, 'What is your full name?'
            = f.text_field :full_name, placeholder: "Jane Smith"

            .fieldlet.go-by{style: @user.go_by_name.present? ? nil : 'display:none'}
              %p{'data-bind' => 'goBySuggestion'}
                = f.hidden_field :go_by_name
                %span{'data-bind' => 'goByQuestion'} Can we call you <strong data-bind='user[go_by_name]'>#{ @user.go_by_name }</strong>?
                %a{'data-action' => 'yes'} Yes
                %a{'data-action' => 'no'} No

              %p{'data-bind' => 'goByOverride', style: 'display:none'}
                = f.label :go_by_name, 'I prefer to go by'
                = f.text_field :go_by_name, placeholder: "Jane"

          .field
            = f.label :first_team_name, 'What is your team called?'
            = f.text_field :first_team_name, placeholder: "e.g. #{ %w(Dev Marketing Product).sample } Team"

        %aside
          .uploader
            - if @user.portrait.present?
              %div.portrait-placeholder{style: "background-image:url(#{ asset_url(@user.portrait.url) }); background-size: cover;"}
            - else
              %div.portrait-placeholder

            %label Upload a portrait. Smile!
            = f.hidden_field(:portrait_cache)
            = f.file_field(:portrait)

        %nav
          / .other-option= link_to raw("I don't plan to use <strong>I Done This</strong> with a team"), '/onboard/exit', method: 'patch'

          .actions= f.submit 'Continue', class: 'button onboard-one-button'

app/views/onboard/onboard_two.html.haml
.wrapper-small{role: 'layout'}
  .onboard-content
    %header.onboard-header
      %h1 Invite to <strong>#{ @team.name }</strong>

  .invitations-panel
    = form_for "/onboard/two", html: { method: 'patch' } do |f|
      %input{type: 'hidden', name: 'invitations[email_addresses]', 'data-bind' => 'emailAddresses'}

      .invitations-panel_omnifield
        %input{type: 'email', placeholder: 'Enter email address', 'data-bind' => 'potentialInvitee'}

      .invitations-panel_potential-invitations
        %ul.invitations-panel_potential-invitations_list
        %div.empty
          :markdown
            Invite team-mates and collaborators by entering email addresses above (one at a time and then press `enter`).

      .invitations-panel_actions
        .other-option= link_to raw("I don't want to invite anybody yet"), '/onboard/exit', method: 'patch'
        %input.button{type: 'submit', value: 'Invite', 'data-verb' => 'Invite'}